<!DOCTYPE html>
<html>
<head>
	<title><?= $this->dispatcher->getControllerName() ?></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<style type="text/css">
		footer {
			background-color: #c1c1c1;
			font-size: small;
			padding: 10px;
			margin-top: 50px;
		}
	</style>
</head>
<body>
	<nav class="nav">
		<a class="nav-link" href="/home">Home</a>
		<a class="nav-link" href="/home/new">New user</a>
		<a class="nav-link" href="/contact">Contact me</a>
	</nav>

	<div class="container">
		<div class="row">
			<div class="col-sm">
				<?= $this->getContent() ?>
			</div>
		</div>
	</div>

	<footer class="text-center">
		<p>My Page &copy; 2019. All rights reserved.</p>
	</footer>
</body>
</html>